# va in html title
title: Urbanistic Projects
# va in html meta description
description: A seminar series on emerging design practices and culture in European cities.
# va in html meta keywords
keywords: urbanistic projects, urbanism, projects, europe, EU, urban planning, urban design, architecture, landscape architecture, landscape urbanism, regional design, ecologial urbanism, landscape infrastructure, territorial project, territory, territories
# va nella navigazione
sitename: Urbanistic Projects
# accessibile con site.url
url: https://urbanisticprojects.eu

kramdown:
  hard_wrap: true
